### PR TITLE
Migrate to netlify cms

### PR DESCRIPTION
**Pull request by DreaMinder**
@martinoroma88 It's not finished yet.
- I fixed multiline titles in some posts
- I switched authors, categories and subcategories from multi-select to a single-select. There's no multiselect widget in netlify CMS, and have to fix UI because of that. Is that OK? Did you want to have multiple authors and categories? 
- Subcategory field doesn't work with the current implementation... do we need it at all? Or is just legacy field?

TODO: 
- fix publication page
- check other pages
- handle no-line-break-symbol using regex:

```
FIND                        REPLACE
[ ]+([:;?!»”])              &nbsp;\1
([«“])[ ]+                   \1&nbsp;
```

### CODE REVIEW

**Comment by martinoroma88** [comment]
Hello Anatoliy,

Thank you. It is ok to have single Author and Categories. Can you handle all those changes usinga different branch? This way we may be able to go live today and continue working in parallel.
Martino

**Comment by martinoroma88** [comment]
Please use different branch to merge those changes

**Comment by DreaMinder** [comment]
So you will work on this branch, and I'll merge my updates from another branch to this branch when ready? ok.,..
As long as we don't touch master-branch, we can go live, just saying.

**Comment by DreaMinder** [comment]
I've pushed final fixes here.
@martinoroma88 I'll resolve conflicts, it's not a problem. But can you go through the preview version and let me know if any regressions? It looks good to me.

**Comment by martinoroma88** [comment]
Hello,

The preview of the articles is fine. Are you editing the code adding &nbsp; while the .md is saved, or are you transforming the output of Nuxt Content fetch API? The latter option could be more solid ?
Do I have to login to Admin as well? I tried without success but did not investigate Netlify setup. Let me know in case I'll do tomorrow.

Now... very tired, going home :)
Thanks for all,

Martino

**Comment by martinoroma88** [comment]
yes... I am touching master branch actually, but in a way that is (hopefully) safe to go online with :)

Martino

**Comment by DreaMinder** [comment]
@martinoroma88 no, this part is not done. 
But are you sure we need it? I don't see any case where text browser adds line-break before punctuation marks. And I didn't find anyone adding this symbol in Web. Maybe it makes sense in typography, but not in web?
BTW, I tested netlify-cms-editor and it not escaping non-break symbol, so at least the manual way works.

**Comment by martinoroma88** [comment]
The fact is that French people add a space between words many characters like ? ! “ etc. for instance: 

 

How are you doing ?

 

Instead of

 

How are you doing?

 

But the question marks and other symbols cannot go to newline, that is why we need &nbsp;

 

Of course we can ask editor to add them, but if he has to do some copy paste from Word (in most cases), it become painful.

 

M.

 

 

Da: DreaMinder <notifications@github.com> 
Inviato: mercoledì 2 dicembre 2020 16:36
A: martinoroma88/ihei-blog <ihei-blog@noreply.github.com>
Cc: Martino Roma <mroma@genesicom.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [martinoroma88/ihei-blog] Migrate to netlify cms (#4)

 

@martinoroma88 <https://github.com/martinoroma88>  no, this part is not done.
But are you sure we need it? I don't see any case where text browser adds line-break before punctuation marks. And I didn't find anyone adding this symbol in Web. Maybe it makes sense in typography, but not in web?
BTW, I tested netlify-cms-editor and it not escaping non-break symbol, so at least the manual way works.

**Comment by DreaMinder** [comment]
@martinoroma88 I fixed merge conflicts, let's merge today? And from now on, please consider that I changed schema to fit netlify CMS: category, author and subcategory fields specifically. If you make changes manually, don't forget about that.

**Pull request merged**
